services:
  clio_develop:
    image: ghcr.io/godexsoft/clio-ci:bf4d1c85e70e01897962a255e052095ed0591811
    volumes:
      - clio_develop_conan_data:/root/.conan2/p
      - clio_develop_ccache:/root/.ccache
      - ../../:/root/clio
      - clio_develop_build:/root/clio/build_docker
    working_dir: /root/clio/build_docker
    tty: true

volumes:
  clio_develop_conan_data:
  clio_develop_ccache:
  clio_develop_build:
