services:
  clio_develop:
    image: ghcr.io/godexsoft/clio-ci:33096b2d9fb7a5e15fc5e64b199ee9d2c2be4c8f
    volumes:
      - clio_develop_conan_data:/root/.conan2/p
      - clio_develop_ccache:/root/.ccache
      - ../../:/root/clio
      - clio_develop_build:/root/clio/build_docker
    working_dir: /root/clio/build_docker
    tty: true

volumes:
  clio_develop_conan_data:
  clio_develop_ccache:
  clio_develop_build:
