name: Run tests with sanitizers
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/sanitizers.yml'

jobs:
  build:
    name: Build clio tests
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: heavy
            sanitizer: tsan
            compiler: gcc
            container:
              image: rippleci/clio_ci:latest
          - os: heavy
            sanitizer: asan
            compiler: gcc
            container:
              image: rippleci/clio_ci:latest
          - os: heavy
            sanitizer: ubsan
            compiler: gcc
            container:
              image: rippleci/clio_ci:latest
    runs-on: [self-hosted, "${{ matrix.os }}"]
    container: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Prepare runner
        uses: ./.github/actions/prepare_runner
        with:
            disable_ccache: true

      - name: Setup conan
        uses: ./.github/actions/setup_conan
        id: conan
        with:
          conan_profile: ${{ matrix.compiler }}.${{ matrix.sanitizer }}

      - name: Run conan and cmake
        uses: ./.github/actions/generate
        with:
          conan_profile: ${{ steps.conan.outputs.conan_profile }}
          conan_cache_hit: false
          build_type: Release
          static: false
          code_coverage: false
          sanitizer: ${{ matrix.sanitizer }}

      - name: Build clio_tests
        uses: ./.github/actions/build_clio
        with:
          target: clio_tests
          substract_threads: 2 # 2 less threads than normal. see if this helps memory on selfhosted runners

      - name: Upload clio_tests
        uses: actions/upload-artifact@v4
        with:
          name: clio_tests_${{ matrix.compiler }}_${{ matrix.sanitizer }}
          path: build/clio_tests

  # consider combining this with the previous matrix instead
  run_tests:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: heavy
            sanitizer: tsan
            compiler: gcc
            container:
              image: rippleci/clio_ci:latest
          - os: heavy
            sanitizer: asan
            compiler: gcc
            container:
              image: rippleci/clio_ci:latest
          - os: heavy
            sanitizer: ubsan
            compiler: gcc
            container:
              image: rippleci/clio_ci:latest
    runs-on: [self-hosted, "${{ matrix.os }}"]
    container: ${{ matrix.container }}
    permissions:
      contents: write
      issues: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: clio_tests_${{ matrix.compiler }}_${{ matrix.sanitizer }}

      - name: Run clio_tests [${{ matrix.compiler }} / ${{ matrix.sanitizer }}]
        shell: bash
        run: |
          chmod +x ./clio_tests
          ./.github/scripts/execute-tests-under-sanitizer ./clio_tests

      - name: Check for sanitizer report
        shell: bash
        id: check_report
        run: |
          if ls .sanitizer-report/* 1> /dev/null 2>&1; then
            echo "found_report=true" >> $GITHUB_OUTPUT
          else
            echo "found_report=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload report
        if: steps.check_report.outputs.found_report == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.compiler }}_${{ matrix.sanitizer }}_report
          path: .sanitizer-report/*
          include-hidden-files: true

      - name: Create an issue
        if: steps.check_report.outputs.found_report == 'true'
        uses: ./.github/actions/create_issue
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          labels: 'bug'
          title: '[${{ matrix.sanitizer }}/${{ matrix.compiler }}] reported issues'
          body: >
            Clio tests failed one or more sanitizer checks when built with ${{ matrix.compiler }}`.

            Workflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/
            Reports are available as artifacts.
